[commandDescriptions]
  about      = "- Bot information"
  choose     = "- This command is used when you select a song from the selection menu."
  discordfm  = "- Plays music from discord.fm playlists"
  dump       = "- Outputs the music queue as a json string"
  help       = "- Shows the help index."
  invite     = "- This command shows an OAuth link to invite the bot to your server."
  move       = "- Moves the bot to a different voice channel"
  nowplaying = "- This command shows the current song."
  pause      = "- Pauses the song. Type ?pause again to start the song."
  play       = "- This command adds a song to the queue and starts playing."
  queue      = "- This shows the song queue."
  radio      = "- Streams UK radio stations"
  reorder    = "- Changes the position of a song in the queue"
  repeat     = "- Loops"
  restart    = "- Plays a song from the start."
  donate     = "- Use this command to find my Patreon and see how you can donate."
  search     = "- Searches for a song on the YouTubes! :musical_note:"
  skip       = "- Plays the next song!"
  stop       = "- This command stops playing music and leaves the voice channel!"
  volume     = "- This command is supposed to change the volume, but is currently disabled."
  acebotdiscord = "- Gives you an invite to the AceBot discord. Pretty simple."
  jump       = "- Use this command to go to a specific part of a song or audio. For example, ?jump 3:52 for 3m and 52s."

[radioStations]
  "Absolute Radio"        = "http://icy-e-bab-09-boh.sharp-stream.com/absoluteradio.mp3"
  "Absolute Radio 80s"    = "http://icy-e-bab-04-cr.sharp-stream.com/absolute80s.mp3.m3u"
  "BBC 1Xtra"             = "http://www.listenlive.eu/bbc1xtra.m3u"
  "BBC Asian Network"     = "http://www.listenlive.eu/bbcasian.m3u"
  "BBC Radio 1"           = "http://www.listenlive.eu/bbcradio1.m3u"
  "BBC Radio 2"           = "http://www.listenlive.eu/bbcradio2.m3u"
  "BBC Radio 3"           = "http://www.listenlive.eu/bbcradio3.m3u"
  "BBC Radio 4"           = "http://www.listenlive.eu/bbcradio4.m3u"
  "BBC Radio 5 Live"      = "http://www.listenlive.eu/bbc5live.m3u"
  "BridgeFM"              = "http://icy-e-03-boh.sharp-stream.com/tcbridge.mp3"
  "CapitalFM"             = "http://media-ice.musicradio.com/CapitalSouthWalesMP3"
  "Cima 100"              = "http://www.surfmusic.de/m3u/cima-100-fm,3447.m3u"
  "ClassicalFM"           = "http://media-ice.musicradio.com/ClassicFMMP3"
  "GGRadio.net"           = "http://sv.ggradio.net:8000/stream"
  "Happy Christmas Radio" = "http://streaming.radionomy.com/HappyChristmasradio"
  "Heart"                 = "http://media-ice.musicradio.com/HeartSouthWalesMP3"
  "Hive365"               = "http://stream.hive365.co.uk:8088/live"
  "KissFM"                = "http://icy-e-ba-09-boh.sharp-stream.com/kissnational.mp3"
  "Los40"                 = "http://19113.live.streamtheworld.com/LOS40.mp3"
  "M-1"                   = "http://stream.m-1.fm/M-1aacp"
  "NonStopPlay"           = "http://www.nonstopplay.com/site/media/pls/midband.pls"
  "NRK mP3"               = "http://nrk-mms-live.online.no/nrk_radio_mp3_aac_h"
  "PowerFM"               = "http://icast.powergroup.com.tr/PowerFM/mpeg/128/home"
  "PowerHitRadio"         = "http://power-stream.data.lt:8000/PHR.mp3"
  "Radio 538"             = "http://vip-icecast.538.lw.triple-it.nl/RADIO538_MP3"
  "Radio Disney"          = "http://radio.domint.net:8026/"
  "Radio Nova Era"        = "http://centova.radios.pt:9478/stream"
  "Record Dance Radio"    = "http://air.radiorecord.ru:805/rr_320"
  "Radio Veronica"        = "http://8543.live.streamtheworld.com/VERONICACMP3"
  "Smooth Radio"          = "http://media-ice.musicradio.com/SmoothSouthWalesMP3"
  "SwanseaSound"          = "http://gbradio.cdn.tibus.net/SWASS"
  "The Breeze"            = "http://stream5.radiomonitor.com/Breeze-Bristol-128"
  "TheWave"               = "http://gbradio.cdn.tibus.net/SWAWave"
  "TSF"                   = "http://tsfdirecto.tsf.pt/tsfdirecto.mp3"

